name: Trigger on Pull Request

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"
