name: CI/CD for Azure ML Environments

# This workflow trains in dev, then (on success + approval) in prod.

on:
  workflow_dispatch:

jobs:
  experiment:
    name: Run experiment (dev)
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Azure login (dev)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEV_CREDENTIALS }}

      - name: Submit experiment job
        run: |
          az ml job create --file src/job.yml \
            --resource-group mslearn-mlops-rg \
            --workspace-name mslearn-mlops-aml \
            --set inputs.training_data.path=azureml:diabetes-dev-folder@latest \
            --stream

  production:
    name: Run production training
    runs-on: ubuntu-latest
    needs: experiment
    if: needs.experiment.result == 'success'
    environment:
      name: production
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Azure login (prod)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_PROD_CREDENTIALS }}

      - name: Submit production job
        run: |
          az ml job create --file src/job.yml \
            --resource-group mslearn-prod-mlops-rg \
            --workspace-name mslearn-prod-mlops-aml \
            --set inputs.training_data.path=azureml:diabetes-prod-folder_2@latest \
            --stream
