name: Deploy production model

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy model to online endpoint
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure login (Production)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_PROD_CREDENTIALS }}

    - name: Install Azure ML extension
      run: az extension add -n ml -y

    - name: Create online endpoint (idempotent)
      run: |
        az ml online-endpoint create \
          --file endpoint.yml \
          --resource-group mslearn-prod-mlops-rg \
          --workspace-name mslearn-prod-mlops-aml \
        || true
    - name: Print deployment file content
      run: |
        echo "--- Content of deployment.yml ---"
        cat deployment.yml
        echo "-----------------------------------"
    - name: Deploy registered model
      run: |
        az ml online-deployment create \
          --file deployment.yml \
          --resource-group mslearn-prod-mlops-rg \
          --workspace-name mslearn-prod-mlops-aml \
          --no-wait
