name: Deploy production model
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Azure login (Production)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_PROD_CREDENTIALS }}

    - name: Install Azure ML extension
      run: az extension add -n ml -y

    - name: Create or update endpoint
      run: |
        az ml online-endpoint create \
          --file endpoint.yml \
          --resource-group mslearn-prod-mlops-rg \
          --workspace-name mslearn-prod-mlops-aml \
        || az ml online-endpoint update \
          --file endpoint.yml \
          --resource-group mslearn-prod-mlops-rg \
          --workspace-name mslearn-prod-mlops-aml

    - name: Deploy registered model
      run: |
        az ml online-deployment create \
          --file deployment.yml \
          --resource-group mslearn-prod-mlops-rg \
          --workspace-name mslearn-prod-mlops-aml

    # (Optional) You can drop this if you're confident traffic: is in endpoint.yml,
    # otherwise keep it to be explicit:
    - name: Route 100% traffic
      run: |
        az ml online-endpoint update \
          --name diabetes-endpoint-xyz3 \
          --resource-group mslearn-prod-mlops-rg \
          --workspace-name mslearn-prod-mlops-aml \
          --traffic diabetes-deployment=100
